  - repo: https://github.com/bridgecrewio/yor
    rev: 0.1.143
    hooks:
      - id: yor
        name: yor-test
        entry: yor tag -d . --config-file custom-tag.yaml
        args: ["."]
        language: golang
        types: [terraform]
        pass_filenames: false