name: 'Terragrunt Plan and apply'
on:
  push:
    branches:
      - master
    paths:
      - '/ec2/**'
    branches:
      - master
    path:
      - '/instance/**'

env:
  tf_version: '1.9.5'
  tg_version: '0.67.0'
  aws_region: 'ap-southeast-3'
  working_dir: 'ec2/instance' 

permissions:
  contents: read
  id-token: write
  pull-requests: write

jpbs: 
  terragrunt:
    name: 'Terragrunt Plan and Apply'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.aws_region }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.tf_version }}

      - name: Set up Terragrunt
        uses: autero1/setup-terragrunt@v2
        with:
          terragrunt_version: ${{ env.tg_version }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.aws_region }}

      - name: Terragrunt Plan
        run: |
          cd ${{ env.working_dir }}
          terragrunt plan --terragrunt-non-interactive --terragrunt-working-dir ${{ env.working_dir }} --terragrunt-include-external-dependencies --terragrunt-config-file terragrunt.hcl
