name: Terragrunt Plan Dong

on:
  push:
    branches:
      - main
    paths:
        # Trigger only for changes in Terraform files
      - 'infra/terraform/**'
  pull_request:
    paths:
      - 'infra/terraform/**'

env:
  tf_version: '1.9.5'
  tg_version: '0.67.0'
  working_dir: 'project'

jobs:
  terragrunt:
    run-ons: ubuntu-latest
    step:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache Terraform and Terragrunt
        uses: actions/cache@v3
        with:
          path: |
            ~/.terraform
            ~/.terragrunt
          key: ${{ runner.os }}-terraform-${{ env.tf_version }}-terragrunt-${{ env.tg_version }}
          restore-keys: |
            ${{ runner.os }}-terraform-
            ${{ runner.os }}-terragrunt-

      - name: Pre-commit checks
        run: |
          pip install pre-commit
          pre-commit run --all-files

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-3

      - name: Init
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: infra/terraform
          tg_command: 'run-all init'

      - name: Validate
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: infra/terraform
          tg_command: 'run-all validate'

      - name: Plan
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: infra/terraform
          tg_command: 'run-all plan'

      - name: Upload Plan File
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: terraform-plan
          path: infra/terraform/*.tfplan

      - name: Apply
        uses: gruntwork-io/terragrunt-action@v2
        if: github.ref == 'refs/heads/main'
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: infra/terraform
          tg_command: 'run-all apply --auto-approve'
